# PID
KP = 1.10
KI = 0.00
KD = 0.18
TURN_LIMIT = 0.80
CENTER_DEADZONE = 0.12
ADAPTIVE_PID_ENABLED = True
ADAPTIVE_KP_ERROR_BOOST = 0.55
ADAPTIVE_KP_CONFIDENCE_DROP = 0.25
ADAPTIVE_KD_ERROR_BOOST = 0.35
ADAPTIVE_KD_DERIVATIVE_BOOST = 0.55
ADAPTIVE_KI_ERROR_REDUCTION = 0.70
ADAPTIVE_DERIVATIVE_REF = 4.0
INTEGRAL_LIMIT = 1.2
LOW_CONFIDENCE_SPEED_SCALE = 0.65
ERROR_SPEED_REDUCTION = 0.55
DERIVATIVE_SPEED_REDUCTION = 0.35
STRAIGHT_SPEED_BOOST = 0.10
CURVE_SPEED_REDUCTION = 0.45
CURVE_TURN_BOOST = 0.35
MIN_CURVE_SPEED_SCALE = 0.45
NEAR_TRAJECTORY_WEIGHT = 0.65
LOOKAHEAD_TRAJECTORY_WEIGHT = 0.35
LOOKAHEAD_CONFIDENCE_MIN = 0.25
RK4_TRAJECTORY_GAIN = 10.0
RK4_HEADING_GAIN = 8.0
RK4_MAX_DT = 0.05

# Second RK4 layer: tracks curvature trend between the lookahead and far ROIs,
# so a closing-out turn can be anticipated before the near ROI ever straightens.
FAR_CONFIDENCE_MIN = 0.25
RK4_CURVATURE_GAIN = 10.0
RK4_CURVATURE_RATE_GAIN = 8.0
CURVATURE_DAMPING = 0.6

# Smooths the discrete error derivative before it feeds the PID/turn-boost math.
# Raw frame-to-frame derivative of a noisy vision error is the classic cause of
# oscillation ("swinging") on turns -- this trades a little responsiveness for
# a lot less overshoot-correct-overshoot.
DERIVATIVE_SMOOTHING = 0.4

# Persistence of vision. The camera is mounted tilted 25 deg forward, so it sees a
# turn before the wheels reach it. The error observed now is held for the travel
# time to that ground patch and only then steered on. Bounded so a bad depth
# sample or a near-stopped robot can't stall or spike the delay.
VISION_DELAY_MIN_S = 0.0
VISION_DELAY_MAX_S = 0.45

# SPEEDS
SHARP_TURN_SPEED = 0.50
MAX_TURN_SPEED = 0.65
STEER_INVERT = True
BASE_SPEED = 0.26
MAX_SPEED = 0.42
MIN_SPEED = 0.1
SPIN_SEARCH_SPEED = 0.32
APPROACH_SPEED = 0.24
LINE_LOST_STOP_TIMEOUT_S = 4.0
SLEW_RATE_PER_S = 0.45
MANUAL_SPEED = 0.22
MANUAL_KEY_TIMEOUT_S = 0.5

# ROI VALUES
ROI_Y_START_RATIO = 0.67
ROI_Y_END_RATIO = 0.86
ROI_X_START_RATIO = 0.05
ROI_X_END_RATIO = 0.85
LOOKAHEAD_ROI_Y_START_RATIO = 0.42
LOOKAHEAD_ROI_Y_END_RATIO = 0.62
LOOKAHEAD_ROI_X_START_RATIO = 0.05
LOOKAHEAD_ROI_X_END_RATIO = 0.85
FAR_ROI_Y_START_RATIO = 0.24
FAR_ROI_Y_END_RATIO = 0.40
FAR_ROI_X_START_RATIO = 0.05
FAR_ROI_X_END_RATIO = 0.85
WIDE_ROI_Y_START_RATIO = 0.20
WIDE_ROI_X_START_RATIO = 0.0
WIDE_ROI_X_END_RATIO = 1.0

# THRESHOLDS
BLACK_THRESHOLD = 90
MIN_LINE_AREA = 45
PICAMERA2_RGB_TO_BGR = False
GREEN_DIFF_THRESHOLD = 40
RED_DIFF_THRESHOLD = 40
MIN_MARKER_AREA = 40
MARKER_ACTION_DELAY_S = 1.0

# Camera
CAMERA_WIDTH = 640
CAMERA_HEIGHT = 480
CAMERA_FPS = 30
USB_CAMERA_INDEX = 0

# Motor pins
LEFT_ENA = 12
LEFT_IN1 = 16
LEFT_IN2 = 20
RIGHT_ENB = 18
RIGHT_IN3 = 21
RIGHT_IN4 = 26
PWM_FREQUENCY_HZ = 1000

# Indicator pins
RED_LED_PIN = 5
GREEN_LED_PIN = 6
BUZZER_PIN = 13

# Acceleration buzzer
ACCEL_BUZZER_ENABLED = True
ACCEL_BUZZER_FREQ_HZ = 220.0
ACCEL_BUZZER_DUTY = 30.0
ACCEL_SPEED_DELTA_THRESHOLD = 0.01

# Intersection detection
INTERSECTION_MIN_CONTOURS = 2
INTERSECTION_MIN_AREA = 40

# Temporal buffer / backtracking
MAX_WAYPOINTS = 50
BACKTRACK_SPEED = 0.18
ROTATE_SPEED = 0.38
BACKTRACK_SEARCH_TIMEOUT_S = 8.0
INTERSECTION_COOLDOWN_S = 2.0
INTERSECTION_MEMORY_MAX_AGE_S = 60.0
ROTATE_SETTLE_TIME_S = 0.25

# Debug
SHOW_DEBUG_VIEW = True
DEBUG_VIEW_EVERY_N_FRAMES = 2
LOOP_LOG_INTERVAL_S = 0.20
ROI_VIEW_SCALE = 3
ARROW_MAX_DEFLECTION_DEG = 65.0

# RealSense & Perspective Configs
CAMERA_TILT_ANGLE_DEG = 25.0
CAMERA_MOUNT_HEIGHT_MM = 150.0

WARP_MATRIX = [
    [1.0, 0.0, 0.0],
    [0.0, 1.0, 0.0],
    [0.0, 0.0, 1.0]
]

# Obstacle Detection
GROUND_DEPTH_TOLERANCE_MM = 40.0 # Anything closer by this amount is an obstacle

# SPI Configuration
SPI_BUS = 0
SPI_DEVICE = 0
SPI_MAX_SPEED_HZ = 1000000
