# PID
KP = 1.10
KI = 0.00
KD = 0.18
TURN_LIMIT = 0.80
CENTER_DEADZONE = 0.12

# SPEEDS
SHARP_TURN_SPEED = 0.32
MAX_TURN_SPEED = 0.40
STEER_INVERT = True
BASE_SPEED = 0.2
MAX_SPEED = 0.35
MIN_SPEED = 0.1
SPIN_SEARCH_SPEED = 0.15
APPROACH_SPEED = 0.22
LINE_LOST_STOP_TIMEOUT_S = 4.0
SLEW_RATE_PER_S = 0.3
MANUAL_SPEED = 0.22
MANUAL_KEY_TIMEOUT_S = 0.5

# ROI VALUES
ROI_Y_START_RATIO = 0.67
ROI_Y_END_RATIO = 0.86
ROI_X_START_RATIO = 0.05
ROI_X_END_RATIO = 0.85
WIDE_ROI_Y_START_RATIO = 0.20
WIDE_ROI_X_START_RATIO = 0.0
WIDE_ROI_X_END_RATIO = 1.0

# THRESHOLDS
BLACK_THRESHOLD = 90
MIN_LINE_AREA = 45
PICAMERA2_RGB_TO_BGR = False
GREEN_DIFF_THRESHOLD = 40
RED_DIFF_THRESHOLD = 40
MIN_MARKER_AREA = 40
MARKER_ACTION_DELAY_S = 1.0

# Camera
CAMERA_WIDTH = 320
CAMERA_HEIGHT = 240
CAMERA_FPS = 120

# Motor pins
LEFT_ENA = 12
LEFT_IN1 = 16
LEFT_IN2 = 20
RIGHT_ENB = 18
RIGHT_IN3 = 21
RIGHT_IN4 = 26
PWM_FREQUENCY_HZ = 1000

# Indicator pins
RED_LED_PIN = 5
GREEN_LED_PIN = 6
BUZZER_PIN = 13

# Intersection detection
INTERSECTION_MIN_CONTOURS = 2
INTERSECTION_MIN_AREA = 40

# Temporal buffer / backtracking
MAX_WAYPOINTS = 50
BACKTRACK_SPEED = 0.15
ROTATE_SPEED = 0.25
BACKTRACK_SEARCH_TIMEOUT_S = 8.0
INTERSECTION_COOLDOWN_S = 2.0
INTERSECTION_MEMORY_MAX_AGE_S = 60.0
ROTATE_SETTLE_TIME_S = 0.25

# Debug
SHOW_DEBUG_VIEW = True
ROI_VIEW_SCALE = 3
ARROW_MAX_DEFLECTION_DEG = 65.0
